INSERT INTO TBL_CATEGORY (ID, NAME) VALUES (1, 'Fabricação Própria')
INSERT INTO TBL_CATEGORY (ID, NAME) VALUES (2, 'Nacional')
INSERT INTO TBL_CATEGORY (ID, NAME) VALUES (3, 'Importado')
INSERT INTO TBL_CATEGORY (ID, NAME) VALUES (4, 'Premium')



INSERT INTO TBL_PRODUCT (ID, NAME, DESC,  PRICE, CATEGORY_ID, PROMOTION, NOVO) VALUES (1, 'ASUS ROG Strix Scar 18','Intel Core i9-14900K' ,1000, 1, FALSE, TRUE)
INSERT INTO TBL_PRODUCT (ID, NAME, DESC, PRICE, CATEGORY_ID, PROMOTION, NOVO) VALUES (2, 'Acer Nitro 5 AN515-58-54UH', 'Intel Core i5-14600KF', 800, 2, TRUE, TRUE)
INSERT INTO TBL_PRODUCT (ID, NAME, DESC, PRICE, CATEGORY_ID, PROMOTION, NOVO) VALUES (3, 'Acer Nitro 5 AN515-58-54UH', 'Intel Core i5-13400', 700, 3, TRUE, FALSE)

